package com.spartaglobal.unittests;

import com.spartaglobal.sortmanager.model.BubbleFactory;
import com.spartaglobal.sortmanager.model.MergeFactory;
import com.spartaglobal.sortmanager.model.NumberArray;
import com.spartaglobal.sortmanager.SorterDriver;
import com.spartaglobal.sortmanager.viewer.SortView;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static com.spartaglobal.sortmanager.model.BubbleSorter.bubbleSort;
import static com.spartaglobal.sortmanager.model.MergeSorter.mergeSort;
import static org.junit.jupiter.api.Assertions.*;

public class SorterTests {


    @Test
    @DisplayName("Testing that program can handle an empty value.")
    public void emptySortTest() {
        int[] actual = {};
        int[] expected = {};
        bubbleSort(actual);
        assertArrayEquals(expected, actual);
    }


    @Test
    @DisplayName("Testing that Merge Sort can correctly sort through an array not generated by Number Array")
    public void positiveMergeTest() {
        int[] actual = { 6, 2, 5, 1, 4, 3 };
        int[] expected = { 1, 2, 3, 4, 5, 6 };
        mergeSort(actual, actual.length);
        assertArrayEquals(expected, actual);
    }

    @Test
    @DisplayName("Testing that Bubble Sort can correctly sort through an array not generated by Number Array")
    public void positiveBubbleTest() {
        int[] actual = {3, 6, 1, 2, 4, 5};
        int[] expected = {1, 2, 3, 4, 5, 6};
        bubbleSort(actual);
        assertArrayEquals(expected, actual);


    }

    @Test
    @DisplayName("Generating an array of numbers")
    public void generateNumberArray() {
        int[] numberTest = NumberArray.arrayOfNumbers();
        String expected = Arrays.toString(numberTest);

    }

    @Test
    @DisplayName("Trying to create a Bubble Sort by calling it through its' factory.")
    public void createBubbleSort() {
        BubbleFactory bubbleFactory = new BubbleFactory();
        bubbleFactory.getInstance();

    }

    @Test
    @DisplayName("Trying to create a Merge Sort by calling it through its' factory.")
    public void createMergeSort() {
        MergeFactory mergeFactory = new MergeFactory();
        mergeFactory.getInstance();
    }

    @Test
    @DisplayName("Given a null array, Bubble sort is expected to throw a NullPointerException")
    public void returnsANullPointerException(){
        int[] numberTest = null;
        NullPointerException nullPointer = assertThrows(NullPointerException.class, () -> bubbleSort(numberTest));
    }

}
